### ISSUE TITLE
OS: Windows - Not writing embedded png file on the directory pointed in extent.properties due to which throws IO Exception

### ISSUE THREAD

**Issue by NerdishShah** [extent-framework/extentreports-cucumber4-adapter#5] opened 2018-12-16 12:02 UTC
On Windows, there is no screenshots written on the pointed directory in extent.properties and throws IO Exception. Please note that the same works fine on Mac platform except that it always writes on first level directory.

**OS:** Windows
**Klov Version:** 0.2.2
**Adapter Version:** 1.2.5

**Using:**

@After
	public void embedScreenshot(Scenario scenario) throws IOException {
		if (scenario.isFailed()) {
			WebDriver driver = DriverManager.getDriver();
			byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
			scenario.embed(screenshot, "image/png");
			if (driver != null) {
				driver.quit();
				driver = null;
			}

	}

**extent.properties**

extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=true
extent.reporter.klov.start=true
extent.reporter.logger.start=true
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=src/test/resources/klov.properties
extent.reporter.logger.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.tabular.out=test-output/TabularReport/

screenshot.dir=test-output/screenshots/

**StackTrace:** 

java.io.IOException: The system cannot find the file specified D:\Dev\My Lab\cucumber4adapter\test-output\screenshots\embedded1.png
	at com.aventstack.extentreports.mediastorage.impl.HttpMediaManagerImplKlov.storeMedia(HttpMediaManagerImplKlov.java:44)
	at com.aventstack.extentreports.mediastorage.KlovMediaStorageHandler.saveScreenCapture(KlovMediaStorageHandler.java:47)
	at com.aventstack.extentreports.reporter.ExtentKlovReporter.saveScreenCapture(ExtentKlovReporter.java:679)
	at com.aventstack.extentreports.reporter.ExtentKlovReporter.onScreenCaptureAdded(ExtentKlovReporter.java:671)
	at com.aventstack.extentreports.ExtentObservable.addScreenCapture(ExtentObservable.java:374)
	at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:363)
	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:308)
	at com.aventstack.extentreports.ExtentTest.info(ExtentTest.java:443)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.handleEmbed(ExtentCucumberAdapter.java:178)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.access$4(ExtentCucumberAdapter.java:168)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$6.receive(ExtentCucumberAdapter.java:115)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$6.receive(ExtentCucumberAdapter.java:1)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
	at cucumber.runner.ThreadLocalRunnerSupplier$SynchronizedEventBus.send(ThreadLocalRunnerSupplier.java:90)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:63)
	at cucumber.runner.Scenario.embed(Scenario.java:58)
	at com.ei.StepDefinitions.TransferSteps.embedScreenshot(TransferSteps.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runner.HookDefinitionMatch.runStep(HookDefinitionMatch.java:16)
	at cucumber.runner.TestStep.executeStep(TestStep.java:63)
	at cucumber.runner.TestStep.run(TestStep.java:49)
	at cucumber.runner.TestCase.run(TestCase.java:48)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:124)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:133)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by foursyth** [comment] 2018-12-16 16:42
Please format your post properly.

Custom file names are not allowed. The adapter follows Cucumber convention of saving screenshots. If you would like this changed, please send in a pull request.

**Comment by NerdishShah** [comment] 2018-12-17 03:53
> Please format your post properly.
> 
> Custom file names are not allowed. The adapter follows Cucumber convention of saving screenshots. If you would like this changed, please send in a pull request.

Sorry about it. I have updated the issue accordingly. Please take a look.

**Comment by anshooarora** [comment] 2018-12-17 17:05
I am unable to reproduce.  I am also closing this as this issue is very difficult to comprehend.  Please format your code properly and make sure your configuration is valid.  If you continue to face issues, you can open a new ticket with properly formatted test+code.  Thank you.

klov.properties
```
mongodb.host=localhost
mongodb.port=27017
mongodb.uri=
klov.host=http://localhost
klov.port=80
klov.project.name=cucumber4
klov.report.name=snapshots
```

extent.properties
```
extent.reporter.html.start=true
extent.reporter.klov.start=true

extent.reporter.html.config=
extent.reporter.klov.config=src/test/resources/klov.properties

extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html

screenshot.dir=test-output/screenshots/shots/
```

Klov:

![image](https://user-images.githubusercontent.com/4107384/50102764-e4ded400-01f3-11e9-8373-df4fb63e7e35.png)

**Closed as completed by anshooarora** 2018-12-17 17:05 UTC
